version: '3.7'
services:
  database:
    container_name: database
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  cache:
    container_name: cache
    image: redis
    restart: always
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus
    restart: always
    ports:
      - 9501:8055
    volumes:
      - ./uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: $KEY
      SECRET: $SECRET

      DB_CLIENT: 'postgres'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_DATABASE: $POSTGRES_DB

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD

networks:
  directus:
